const SCENE_WIDTH = 800;
const SCENE_HEIGHT = 600;
const SCENE_BORDER = 5;

const DIRECTION_LEFT = 0;
const DIRECTION_UP = 1;
const DIRECTION_RIGHT = 2;
const DIRECTION_DOWN = 3;

const INITIAL_TANK_X = 0.0;
const INITIAL_TANK_Y = 0.0;
const INITIAL_TANK_DIRECTION = DIRECTION_UP;
const INITIAL_TANKS_WIDTH = 60;
const INITIAL_TANKS_HEIGHT = 60;
const INITIAL_BULLET_X = INITIAL_TANK_X;
const INITIAL_BULLET_Y = INITIAL_TANK_Y;
const INITIAL_BULLET_SIZE = 10;
const INITIAL_BULLET_DIRECTION = INITIAL_TANK_DIRECTION;

const LEFT_BORDER = -SCENE_WIDTH / 2;
const RIGHT_BORDER = SCENE_WIDTH / 2;
const UP_BORDER = SCENE_HEIGHT / 2;
const DOWN_BORDER = -SCENE_HEIGHT / 2;

const KEY_CODE_SPACE = 32;
const KEY_CODE_LEFT = 37;
const KEY_CODE_UP = 38;
const KEY_CODE_RIGHT = 39;
const KEY_CODE_DOWN = 40;

const TANK_STEP = 2;
const BULLET_STEP = 1;